version: "3.9"

services:
  proxy:
    image: nginx:1-alpine
    # Map external directory to internal container directory
    volumes: 
    - ./nginx_configs/:/etc/nginx/conf.d/:ro
    - ./proxy/:/usr/share/nginx/html/:ro
    ports:
      - "8080:80"
    networks:
      - internal-network
  service_sample:
    image: nginx:1-alpine
    hostname: service_sample
    volumes:
      - ./service_sample/:/usr/share/nginx/html/:ro
    networks:
      - internal-network

networks:
  internal-network:
    